[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
itertools = "0.13.0"
regex = "1.11.1"
anyhow = "1.0.93"
indoc = "2.0.5"
strum = { version = "0.26.3", features = ["derive"] }
hashbrown = "0.15.2"
