[package]
name = "day17_transpiler"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.9"
proc-macro2 = "1.0.30"
syn = { version = "1.0.77", features = ["parsing"] }
